"""parent student association table 4

Revision ID: 1100558e2cc9
Revises: 5a7fbf31bfa5
Create Date: 2014-03-28 16:17:22.866686

"""

# revision identifiers, used by Alembic.
revision = '1100558e2cc9'
down_revision = '5a7fbf31bfa5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid_parent_association_table',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kid_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'kid_id')
    )
    op.drop_table(u'mentor_to_mentee')
    op.drop_table(u'student_to_parent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'student_to_parent',
    sa.Column(u'parents', sa.INTEGER(), nullable=False),
    sa.Column(u'kids', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['kids'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['parents'], [u'users.id'], ),
    sa.PrimaryKeyConstraint(u'parents', u'kids')
    )
    op.create_table(u'mentor_to_mentee',
    sa.Column(u'mentors', sa.INTEGER(), nullable=False),
    sa.Column(u'mentees', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mentees'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['mentors'], [u'users.id'], ),
    sa.PrimaryKeyConstraint(u'mentors', u'mentees')
    )
    op.drop_table('kid_parent_association_table')
    ### end Alembic commands ###
