"""8

Revision ID: 1d7c883d6a0d
Revises: f8d23cd8191
Create Date: 2014-03-28 20:46:44.563527

"""

# revision identifiers, used by Alembic.
revision = '1d7c883d6a0d'
down_revision = 'f8d23cd8191'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
