"""added teacher backref in User

Revision ID: 1e4cbee46e8
Revises: 25dc8c72d2bf
Create Date: 2014-03-28 13:55:06.616789

"""

# revision identifiers, used by Alembic.
revision = '1e4cbee46e8'
down_revision = '25dc8c72d2bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
