"""another

Revision ID: 2045cb3d7a6b
Revises: 569bd7b81188
Create Date: 2014-03-26 23:58:45.617836

"""

# revision identifiers, used by Alembic.
revision = '2045cb3d7a6b'
down_revision = '569bd7b81188'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
