"""fixed backrefs

Revision ID: 20a176d08f41
Revises: 3f3e0f161b5e
Create Date: 2014-03-28 14:07:14.943910

"""

# revision identifiers, used by Alembic.
revision = '20a176d08f41'
down_revision = '3f3e0f161b5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
