"""added teacher project association table

Revision ID: 25dc8c72d2bf
Revises: 413ded67af2e
Create Date: 2014-03-28 13:45:31.472047

"""

# revision identifiers, used by Alembic.
revision = '25dc8c72d2bf'
down_revision = '413ded67af2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_to_project',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_to_project')
    ### end Alembic commands ###
