"""2

Revision ID: 30f8556ae588
Revises: 275df1efccf
Create Date: 2014-03-28 19:41:29.712397

"""

# revision identifiers, used by Alembic.
revision = '30f8556ae588'
down_revision = '275df1efccf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
