"""0

Revision ID: 3cb481bb82a6
Revises: 822649f80b3
Create Date: 2014-03-28 20:48:48.327803

"""

# revision identifiers, used by Alembic.
revision = '3cb481bb82a6'
down_revision = '822649f80b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
