"""6

Revision ID: 3d8eec94b9a9
Revises: 3ec4ff2461dd
Create Date: 2014-03-28 19:50:32.968879

"""

# revision identifiers, used by Alembic.
revision = '3d8eec94b9a9'
down_revision = '3ec4ff2461dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
