"""5

Revision ID: 3ec4ff2461dd
Revises: 57ca0cf95e25
Create Date: 2014-03-28 19:48:38.056555

"""

# revision identifiers, used by Alembic.
revision = '3ec4ff2461dd'
down_revision = '57ca0cf95e25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
