"""parent student association table 2

Revision ID: 3ecf99d2eef0
Revises: 4c82fe61d1e4
Create Date: 2014-03-28 15:59:02.820057

"""

# revision identifiers, used by Alembic.
revision = '3ecf99d2eef0'
down_revision = '4c82fe61d1e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid_parent_association_table',
    sa.Column('kid_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kid_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('kid_id', 'parent_id')
    )
    op.drop_table(u'student_to_parent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'student_to_parent',
    sa.Column(u'parents', sa.INTEGER(), nullable=False),
    sa.Column(u'kids', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['kids'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['parents'], [u'users.id'], ),
    sa.PrimaryKeyConstraint(u'parents', u'kids')
    )
    op.drop_table('kid_parent_association_table')
    ### end Alembic commands ###
