"""3

Revision ID: 3f3e0f161b5e
Revises: 1e4cbee46e8
Create Date: 2014-03-28 14:02:02.040328

"""

# revision identifiers, used by Alembic.
revision = '3f3e0f161b5e'
down_revision = '1e4cbee46e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
