"""3

Revision ID: 403886b78f6
Revises: 30f8556ae588
Create Date: 2014-03-28 19:43:41.789384

"""

# revision identifiers, used by Alembic.
revision = '403886b78f6'
down_revision = '30f8556ae588'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
