"""mig

Revision ID: 41838cba2848
Revises: 4c51859d681d
Create Date: 2014-03-24 14:41:23.955736

"""

# revision identifiers, used by Alembic.
revision = '41838cba2848'
down_revision = '4c51859d681d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('help_wanted', sa.String(length=140), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'help_wanted')
    ### end Alembic commands ###
