"""fixed project backrefs

Revision ID: 4a855b65f696
Revises: 1cc15fc688df
Create Date: 2014-03-26 14:12:50.804036

"""

# revision identifiers, used by Alembic.
revision = '4a855b65f696'
down_revision = '1cc15fc688df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
