"""stuff

Revision ID: 4c51859d681d
Revises: 65779cc6c2b
Create Date: 2014-03-24 00:02:14.943797

"""

# revision identifiers, used by Alembic.
revision = '4c51859d681d'
down_revision = '65779cc6c2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
