"""parent student association table

Revision ID: 4c82fe61d1e4
Revises: 20a176d08f41
Create Date: 2014-03-28 15:52:45.397624

"""

# revision identifiers, used by Alembic.
revision = '4c82fe61d1e4'
down_revision = '20a176d08f41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_to_parent',
    sa.Column('parents', sa.Integer(), nullable=False),
    sa.Column('kids', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kids'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parents'], ['users.id'], ),
    sa.PrimaryKeyConstraint('parents', 'kids')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_to_parent')
    ### end Alembic commands ###
