"""superquest changes

Revision ID: 4cde5da35c4c
Revises: 4a855b65f696
Create Date: 2014-03-26 15:08:43.922125

"""

# revision identifiers, used by Alembic.
revision = '4cde5da35c4c'
down_revision = '4a855b65f696'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_to_mentee', sa.Column('mentees', sa.Integer(), nullable=False))
    op.drop_column('mentor_to_mentee', u'mentee')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentor_to_mentee', sa.Column(u'mentee', sa.INTEGER(), nullable=False))
    op.drop_column('mentor_to_mentee', 'mentees')
    ### end Alembic commands ###
