"""parent student association table 5

Revision ID: 53fe1645a4de
Revises: 1100558e2cc9
Create Date: 2014-03-28 16:37:33.759704

"""

# revision identifiers, used by Alembic.
revision = '53fe1645a4de'
down_revision = '1100558e2cc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
