"""4

Revision ID: 57ca0cf95e25
Revises: 403886b78f6
Create Date: 2014-03-28 19:47:00.099820

"""

# revision identifiers, used by Alembic.
revision = '57ca0cf95e25'
down_revision = '403886b78f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
