"""parent student association table 3

Revision ID: 5a7fbf31bfa5
Revises: 3ecf99d2eef0
Create Date: 2014-03-28 16:03:39.101037

"""

# revision identifiers, used by Alembic.
revision = '5a7fbf31bfa5'
down_revision = '3ecf99d2eef0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_to_parent',
    sa.Column('parents', sa.Integer(), nullable=False),
    sa.Column('kids', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kids'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parents'], ['users.id'], ),
    sa.PrimaryKeyConstraint('parents', 'kids')
    )
    op.drop_table(u'kid_parent_association_table')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'kid_parent_association_table',
    sa.Column(u'kid_id', sa.INTEGER(), nullable=False),
    sa.Column(u'parent_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['kid_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint(u'kid_id', u'parent_id')
    )
    op.drop_table('student_to_parent')
    ### end Alembic commands ###
