"""2

Revision ID: 65779cc6c2b
Revises: 3250172f1ee4
Create Date: 2014-03-23 19:19:07.380177

"""

# revision identifiers, used by Alembic.
revision = '65779cc6c2b'
down_revision = '3250172f1ee4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('schools', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'schools')
    ### end Alembic commands ###
