"""9

Revision ID: 822649f80b3
Revises: 1d7c883d6a0d
Create Date: 2014-03-28 20:47:46.573379

"""

# revision identifiers, used by Alembic.
revision = '822649f80b3'
down_revision = '1d7c883d6a0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
