"""another

Revision ID: ff90caf68d7
Revises: 41838cba2848
Create Date: 2014-03-25 23:17:58.080432

"""

# revision identifiers, used by Alembic.
revision = 'ff90caf68d7'
down_revision = '41838cba2848'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expertise', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expertise')
    ### end Alembic commands ###
